In [1]:
import Gauntlets
import math
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
new_gauntlet = Gauntlets.GauntletApp(0)

In [3]:
new_gauntlet.new_random_event()

In [4]:
new_gauntlet.current_event

In [5]:
new_gauntlet.run_event()

Running Event: <Event | ID: 71021 | Owner ID: 0>
Start Time: 2021-01-05 04:06:25.514894
End Time: 2021-01-05 04:06:25.514894
Test Time: 0:00:05.472949
Rows Generated: 1512000

In [26]:
data_points = ['row_number', 'event', 'gauntlet', 'trial', 'time', 'day', 'participant_first_name', 'participant_last_name', 'status', 'perfect_progress', 'success_value', 'influencer_first_name', 'influencer_last_name', 'influencer_attribute_1', 'influencer_attribute_2']

for attribute in new_gauntlet.current_event.teams[0].participants[0].attributes.keys():
    data_points.append(f'participant_{attribute}')

test_data = pd.DataFrame.from_dict(new_gauntlet.runs[0]['data'], orient='index', columns=data_points)

In [27]:
test_data

,row_number,event,gauntlet,trial,time,day,participant_first_name,participant_last_name,status,perfect_progress,success_value,influencer_first_name,influencer_last_name,influencer_attribute_1,influencer_attribute_2,participant_minor_1,participant_minor_2,participant_minor_3,participant_minor_4,participant_major
1,1,chollas,sculpins,nonresonant,1,1,mammers,haricot,resting,0,37776.00,cook,aguishly,5,3,2,4,3,37776,37776.0
2,2,chollas,sculpins,nonresonant,1,1,prehardens,toolings,resting,0,19588.00,cook,aguishly,5,3,10,7,10,19588,19588.0
3,3,chollas,sculpins,nonresonant,1,1,paddywacked,flamen,resting,0,8869.00,cook,aguishly,5,3,3,6,3,8869,8869.0
4,4,chollas,sculpins,nonresonant,1,1,meanwhiles,restacked,resting,0,38027.00,cook,aguishly,5,3,10,1,9,38027,38027.0
5,5,chollas,sculpins,nonresonant,1,1,dauber,vascularities,resting,0,38180.00,cook,aguishly,5,3,1,8,10,38180,38180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1511996,1511996,chollas,sculpins,giftware,151200,106,realtor,exanthema,resting,3600000,0.13,cook,aguishly,5,3,1,6,10,34328,452163.0
1511997,1511997,chollas,sculpins,giftware,151200,106,pitchpoles,participatory,resting,3600000,0.09,cook,aguishly,5,3,1,3,6,7243,335795.5
1511998,1511998,chollas,sculpins,giftware,151200,106,scapular,unrests,resting,3600000,0.58,cook,aguishly,5,3,5,6,4,14695,2103870.0
1511999,1511999,chollas,sculpins,giftware,151200,106,supers,overimpress,resting,3600000,0.65,cook,aguishly,5,3,6,5,2,24696,2352786.0
1512000,1512000,chollas,sculpins,giftware,151200,106,canolas,reveilles,resting,3600000,0.43,cook,aguishly,5,3,5,2,7,26690,1546977.5

In [28]:
start_progress = test_data.iloc[[0, -10]].participant_major

In [29]:
start_progress

1           37776.0
1511991    754166.0
Name: participant_major, dtype: float64

In [30]:
end_progress = test_data.iloc[[-1, -11]]

In [31]:
end_progress

,row_number,event,gauntlet,trial,time,day,participant_first_name,participant_last_name,status,perfect_progress,success_value,influencer_first_name,influencer_last_name,influencer_attribute_1,influencer_attribute_2,participant_minor_1,participant_minor_2,participant_minor_3,participant_minor_4,participant_major
1512000,1512000,chollas,sculpins,giftware,151200,106,canolas,reveilles,resting,3600000,0.43,cook,aguishly,5,3,5,2,7,26690,1546977.5
1511990,1511990,chollas,sculpins,giftware,151199,105,canolas,reveilles,None,3600000,0.43,cook,aguishly,5,3,5,2,7,26690,1546977.5

In [44]:
end_result = test_data[['perfect_progress', 'success_value', 'participant_major']]
end_result

         perfect_progress  success_value  participant_major
1                       0       37776.00            37776.0
2                       0       19588.00            19588.0
3                       0        8869.00             8869.0
4                       0       38027.00            38027.0
5                       0       38180.00            38180.0
...                   ...            ...                ...
1511996           3600000           0.13           452163.0
1511997           3600000           0.09           335795.5
1511998           3600000           0.58          2103870.0
1511999           3600000           0.65          2352786.0
1512000           3600000           0.43          1546977.5

[1512000 rows x 3 columns]

151200

KeyError: ('participant_major', 'success_value')